Browser flow implementation of ORY Kratos self-service with ReactJS
ory/kratos-selfservice-ui-react-nextjs pull request #2
Opened 2021-03-22 19:40 UTC by dduzgun-security

Used the Browser flow to implement ORY Kratos self-service

- Login
- Register
- Logout
- Recover (needs some work)
- Error

I'm still a noob at ReactJS, so feel free to edit the PR if needed 😄

2021-03-22 19:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/kratos-selfservice-ui-react?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/kratos-selfservice-ui-react?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/kratos-selfservice-ui-react?pullRequest=2) it.</sub>

2021-03-22 20:37 UTC, zepatrik commented
Awesome :heart_eyes: you probably want to check this out @vinckr @Benehiko

2021-03-24 14:38 UTC, aeneasr commented
Oh wow this looks cool! I need to check this out with a bit of patience. I will try to do so next week - but great job for working on this!!

2021-03-25 16:56 UTC, Benehiko commented on frontend/src/pages/Dashboard.js
> +import React, { useState } from "react";
```suggestion
import React, { useEffect, useState } from "react";
```

2021-03-25 16:57 UTC, Benehiko commented on frontend/src/pages/Dashboard.js
> +import React, { useState } from "react";
This causes an error so just add that and it should fix it :)

2021-03-25 16:58 UTC, Benehiko commented
This looks really good @dduzgun-security :100: 
Are you planning on adding any user-feedback type error messages like "Incorrect username and password" when the account does not exists etc?

2021-03-25 17:09 UTC, dduzgun-security commented
@Benehiko I'm glad you enjoy it 👍  Yes, I had questions regarding the error handling. Since the flow is all done via Browser form submits and it looks like AJAX calls will be supported in future versions (https://github.com/ory/kratos/discussions/986), do you know a way to get the HTTP response of a submitted form so that the UI can prompt an error message? Any hints would help, I'll try to work on that this weekend.

2021-03-25 17:18 UTC, dduzgun-security commented on frontend/src/pages/Dashboard.js
> +import React, { useState } from "react";
Thank you for the review 😊

2021-03-26 12:47 UTC, Benehiko commented
> @Benehiko I'm glad you enjoy it  Yes, I had questions regarding the error handling. Since the flow is all done via Browser form submits and it looks like AJAX calls will be supported in future versions ([ory/kratos#986](https://github.com/ory/kratos/discussions/986)), do you know a way to get the HTTP response of a submitted form so that the UI can prompt an error message? Any hints would help, I'll try to work on that this weekend.

It's supposed to be redirecting your UI to the `/error` endpoint. https://www.ory.sh/kratos/docs/self-service/flows/user-facing-errors.

The other option is to call kratos using axios or something and then setting the content-type to `'application/x-www-form-urlencoded'`. This will indeed change in future and will be fully supported.

2021-03-26 14:46 UTC, Benehiko commented
I'll add some stuff just now, I'm also investigating why the UI isn't redirecting to the error page.

2021-03-26 22:43 UTC, dduzgun-security commented
Sounds good, I'll take a look at it. 👌
Created a quick kanban with items I'll try to work on this weekend: https://github.com/dduzgun-security/kratos-selfservice-ui-react/projects/1

2021-03-29 09:35 UTC, Benehiko commented
@dduzgun-security you can get the error messages by just getting all the `messages` from the `flow` data you are already retrieving from the `loginFlow` api.
```
const [loginMessages, setLoginMessages] = useState();
setLoginMessages(flow.methods.password.config.messages)

...
and then in your HTML
...

<p>{loginMessages}</p>
```

You can also add in a router guard to always take the user to the dashboard except for if they have no session, which means login page.

2021-03-30 06:15 UTC, dduzgun-security commented
@Benehiko I added the suggested changes for the error messages and the guarded routes.

2021-03-30 07:19 UTC, Benehiko commented on kratos/configs/kratos.yml
> +  level: debug
```suggestion

```
It's already defined later in the config :)

2021-03-30 07:21 UTC, Benehiko reviewed
It's looking good so far!

I'm currently getting an error though after registering an account for instance.
Flow:
register -> dashboard (error)
![image](https://user-images.githubusercontent.com/18033717/112949299-5b8c0b00-9139-11eb-891e-25d801622cd4.png)

2021-03-30 14:57 UTC, atymchuk requested changes

2021-03-30 14:57 UTC, atymchuk commented on frontend/src/App.js
> +            <GuardedRoute path="/dashboard" exact component={Dashboard} meta={{ auth: true }} />
```suggestion
```
You already have the same on line 48, so consider moving that block up here for DRY.

2021-03-30 14:57 UTC, atymchuk commented on frontend/src/pages/Dashboard.js
> +    window.location.href = "http://127.0.0.1:4433/self-service/browser/flows/logout";
Consider extracting this to a variable, like `const host = 'http://127.0.0.1:4433'`, and then just re-use it everywhere you need to.

2021-03-30 14:57 UTC, atymchuk commented on frontend/src/pages/Dashboard.js
> +            </ListItem>
nit: `ListItem` be better right-indented

2021-03-30 14:57 UTC, atymchuk commented on frontend/src/pages/Error.js
> +export default Error;
nit: need eol here

2021-03-30 14:57 UTC, atymchuk commented on frontend/src/pages/Login.js
> +  const [loginMessages, setLoginMessages] = useState(undefined);
```suggestion
  const [loginMessages, setLoginMessages] = useState();
```
`undefined` is always the default, so it can be skipped.

2021-03-30 14:57 UTC, atymchuk commented on frontend/src/pages/Login.js
> +            if (status === 404 || status === 410 || status === 403) {
```suggestion
            if ([401, 403, 404].includes(status)) {
```
Much less verbose :) And I guess it's 401 vs 410, right?

2021-03-30 14:57 UTC, atymchuk commented on frontend/src/pages/Login.js
> +                  : (<>
it should be `null`, which won't render anything.

2021-05-24 07:33 UTC, aeneasr commented
Man, sorry for leaving this uncommented. This is great work! I haven’t merged it yet as we are working on better SDKs and flows for SPAs, AJAX and React! You can take a peek here: https://github.com/ory/kratos/pull/1367

Once merged I’ll come back to this PR, make some adjustments, and merge :)

2021-05-25 03:40 UTC, sbussard commented
@Benehiko I ran into the same problem

> It's looking good so far!
> 
> I'm currently getting an error though after registering an account for instance.
> Flow:
> register -> dashboard (error)
> ![image](https://user-images.githubusercontent.com/18033717/112949299-5b8c0b00-9139-11eb-891e-25d801622cd4.png)

And found this in the kratos.yml

>    cors:
>      enabled: true
>      allowed_origins:
>        - http://127.0.0.1:3000

When I opened the page `http://127.0.0.1:3000` it worked, but it didn't work with localhost

2021-05-25 03:43 UTC, sbussard commented on frontend/src/pages/Dashboard.js
> +    window.location.href = "http://127.0.0.1:4433/self-service/browser/flows/logout";
@dduzgun-security to handle env vars on the client side I usually add script tag inside the index.html to include a /configuration.js which holds something like `window.configuration = { ... }` which can be picked up by the app later. This has the added benefit that the same exact build can live in all environments but the configuration.js will be swapped out

2021-05-31 19:28 UTC, dduzgun-security commented
@aeneasr no worries keep the good work going 👍  Once the AJAX calls are released I can edit the PR to use it.

2021-08-03 12:32 UTC, Benehiko commented
@dduzgun-security https://github.com/ory/kratos/pull/1367 has been merged and v0.7 has been released with AJAX support! :)
https://www.ory.sh/kratos/docs/self-service/flows/user-registration#registration-for-client-side-ajax-browser-clients

Would you still be up for adding the AJAX flows?

2021-08-11 15:06 UTC, dduzgun-security commented
@Benehiko I am currently on vacation but plan to rework that. Was planning to make a blog when (more like if 🥲) I have some extra time.

2021-08-31 08:22 UTC, aeneasr commented
Hello there, just wanted to let you know that I am restructuring the repo a bit. Was a bit of a mistake (I should have renamed this one)!

The new repository will be here: https://github.com/ory/react-nextjs-example

I will be closing this PR here and will also archive the repo. Feel free to reopen the PR at https://github.com/ory/react-nextjs-example/issues and also discuss any ideas there :)

2021-08-31 08:22 UTC, closed without merging